### ISSUE TITLE
关于改善 csl 开发流程的一个小想法：在 generate.js 监听 src/

### ISSUE THREAD

**Issue by northword** [zotero-cn/styles#11]
有个想法，可以在 `lib/generate.js` 加入对 `src/` 的监听，当有 `.csl` 文件修改时，自动生成 markdown 内容，
而 vuepress dev 运行状态时是自动监听了 `.md` 文件的，因此就可以自动生成网页。

这样免去了每次修改 csl 后需要手动运行一下 `yarn generate`。

也就是，在 `generate.js` 中加入监听后，可以实现 csl 修改 -> 网页更新，基本可以实现实时预览更改效果（当然会有那么几秒钟运行延迟，估计在 5 秒左右）。

不知道这种对工作流帮助大不大。

同时也把之前被删掉的用来测试的示例数据加进去，通过环境变量辨别开发环境还是生产环境，本地开发时就将这些测试内容一并输出。

**Comment by zepinglee** [comment]
其实我自己习惯了命令行编译，没觉得麻烦麻烦。@redleafnew 对这个功能感兴趣吗？

测试的数据我觉得可以 commit 到仓库中，比如另存为 `test.md`，这样可以更好地跟踪 .csl 的修改效果，但不在网页的示例中显示。不顾最近开发的需要不大，这个功能优先级可以放低一些。

另外我最近刚发现 https://github.com/Juris-M/citeproc-test-runner 也有测试 .csl 的功能。哪天有时间我去看一下有没有什么值得借鉴。

**Comment by redleafnew** [comment]
> 其实我自己习惯了命令行编译，没觉得麻烦。@redleafnew 对这个功能感兴趣吗？
> 
> 测试的数据我觉得可以 commit 到仓库中，比如另存为 `test.md`，这样可以更好地跟踪 .csl 的修改效果，但不在网页的示例中显示。不顾最近开发的需要不大，这个功能优先级可以放低一些。
> 
> 另外我最近刚发现 https://github.com/Juris-M/citeproc-test-runner 也有测试 .csl 的功能。哪天有时间我去看一下有没有什么值得借鉴。

不懂啊，以前Juris-M的作者提到过用命令行测试，如果有命令行的最好了。

**Comment by zepinglee** [comment]
@northword 你的想法是需要先在命令行运行某个命令，让它在后台一直跑着，当检测到 .csl 有变化时自动生成对应的 markdown？

**Comment by northword** [comment]
> @northword 你的想法是需要先在命令行运行某个命令，让它在后台一直跑着，当检测到 .csl 有变化时自动生成对应的 markdown？

是的，在 generate.js 里加入 watcher 相关的模块/函数，当运行时传入了参数 watch ，就监听 src 文件夹，如果有 csl 更改，就自动生成相应的 markdown。
如果运行时没有传入参数，就不监听。

csl 修改结束后可以结束掉进程。

**Comment by redleafnew** [comment]
> 其实我自己习惯了命令行编译，没觉得麻烦。@redleafnew 对这个功能感兴趣吗？
> 
> 测试的数据我觉得可以 commit 到仓库中，比如另存为 `test.md`，这样可以更好地跟踪 .csl 的修改效果，但不在网页的示例中显示。不顾最近开发的需要不大，这个功能优先级可以放低一些。
> 
> 另外我最近刚发现 https://github.com/Juris-M/citeproc-test-runner 也有测试 .csl 的功能。哪天有时间我去看一下有没有什么值得借鉴。

现在测试有什么好的工具吗？这个CSL Test Suite不知道怎么用。
