### ISSUE TITLE
统一 CSL 样式的 ID 和名称

### ISSUE THREAD

**Issue by zepinglee** [zotero-cn/styles#12]
目前有些样式的名称和 ID 不够统一，不利于检索。拟将全部样式按照以下格式统一（参考 [STYLE_REQUIREMENTS.md](https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md)）：

1. 中文期刊名称使用中文全称：“[Accounting Research](https://zotero-cn.github.io/styles/accounting-research/)” => “会计研究”。
2. 期刊 ID 使用全程（[STYLE_REQUIREMENTS.md#1---title-abbreviations](https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#1---title-abbreviations)）：`cma.csl` => `chinese-medical-association.csl`。
3. 学位论文的名称使用官网的称呼（如“研究生学位论文”），不使用“硕博论文”这样的表述。
4. 学位论文的 ID 使用大学的全称，并且带 thesis 后缀（为了同某些大学的学报区分开）：`hzau-thesis.csl` => `huazhong-agricultural-university-thesis.csl`。

**Comment by northword** [comment]
+1


ID CSL 1.0.2 规范说要到 uuid 4 [^uuid-doc]，issue 里也有成员提了这个[^uuid-issue]，但是可能是因为兼容性考虑，一直没有实施，连仓库的要求都没改，我们也还是可以继续保持 zotero 链接的这种。

[^uuid-doc]:https://docs.citationstyles.org/en/stable/specification.html#info
[^uuid-issue]:https://github.com/citation-style-language/styles/issues/5813

**Comment by zepinglee** [comment]
嗯，我也觉得先按照官方仓库目前的格式吧。
