### ISSUE TITLE
增加测试文件

### ISSUE THREAD

**Issue by zepinglee** [zotero-cn/styles#16]
我在 [test](https://github.com/zotero-cn/styles/tree/test) 分支中将每个样式的输出分为 sample 和 test 两部分。前者是为了在网页中进行简单的展示，后者是为了方便样式开发者每次修改后记录输出的变化，比如《法学引注手册》的 [src/manual-of-legal-citation-multi-lingual/test.md](https://github.com/zotero-cn/styles/blob/test/src/manual-of-legal-citation-multi-lingual/test.md)。

用于测试的输出比较冗余，这也是为了更容易发现 bug。比如 [src/manual-of-legal-citation-multi-lingual/test.md](https://github.com/zotero-cn/styles/blob/test/src/manual-of-legal-citation-multi-lingual/test.md) 就有 800 多行。然而这样的代价是每次 `yarn generate` 需要更长的时间，比如在我的机器上大约 20 秒。

@northword 有什么建议？

**Comment by northword** [comment]
似乎没有更好的办法，我对代码性能优化不大了解，也许测试的可以不用每次都全部输出？就是调试某个样式的时候只生成这一个样式的，可以通过传入参数来控制生成哪个样式？

或者就是之前提到过的监听，通过引入 Chokidar 可以监听有改动的文件 https://www.bilibili.com/read/cv5011048/ ，然后我们只生成这个文件的信息，这样每次改动后就可以节约不少时间。

**Comment by northword** [comment]
我提交了一个简单的想法示例，初次运行可能需要 `yarn install` 或 `yarn add chokidar` 来安装一下依赖。

然后执行 `yarn dev` 生成预览 （无需再次执行 `yarn generate`）（区别仅在于给 `lib/generate.js`加了个 `watch` 参数）。

初次启动会生成所有的，会比较慢，像你说的二十秒的样子，这一步完成后就监听 src/ ，有更改的就重新生成。
（我在想是不是可以初次启动直接监听，免去生成所有的这一步，因为如果正常使用，没有更改的 csl 文件的预览应当是正确的）

你看下效果呢？
（只是简单的写了下，这段时间有点其他事儿，所以可能不太完善来着

**Comment by zepinglee** [comment]
感觉传入参数更简单一些。我再研究一下这个 chokidar。

目前我对 JavaScript 以及其生态不太熟，已有的代码主要靠 stackoverflow 写的。

**Comment by northword** [comment]
> 感觉传入参数更简单一些。我再研究一下这个 chokidar。
> 
> 目前我对 JavaScript 以及其生态不太熟，已有的代码主要靠 stackoverflow 写的。

（我也不太熟，主要是面向搜索引擎编程，每次写完一个都关一大堆标签页

现在就是传入参数的，只不过传入的参数是用来启用 chokidar 的，不是 csl 的路径，

手动输入参数的话是比较麻烦，尤其要传入csl路径的话。所以 chokidar 应该是比较方便的。

后续也可以加入判断传入参数是不是csl路径，如果是路径就只生成这一个。
