### ISSUE TITLE
Markdown 预览保存在了什么地方

### ISSUE THREAD

**Issue by zepinglee** [zotero-cn/styles#4]
我对网页的部署不太了解，请教一下 @northword 生成的预览文件 `docs/preview/{uuid.md}` 似乎没有上传到 GitHub 仓库中。但是<https://zotero-cn.github.io/styles/preview/301manual-of-legal-citation-multi-lingual.html> 可以显示这些预览，在我的理解中这里显示的应该是静态网页，所以用于显示的预览文件保存在了什么地方？

**Comment by northword** [comment]
稍等，我正在用 js 重写，因为发现 citeproc-js-serve 不支持二级目录里的 csl 文件，这样就不符合我们之前的讨论了。

生成的预览 md 文件目前是不提交的（考虑到这些文件本质上无用，就会让 git 记录很乱），在 docs/preview/ 产生后，vuepress将其构建为 html ，html 部署在 gh-pages 分支。

之后用 js 写了的我计划直接把 md 文件存在 csl 边上。

**Comment by zepinglee** [comment]
原来是在 `gh-pages` 分支。

**Comment by northword** [comment]
现在把脚本产生的 markdown 文件放在了 csl 文件旁边，每次 csl 文件有变化时，actions bot 会将更新的 markdown 文件提交回仓库。

本地开发时只需将您习惯的 `node ./generate.js` 更换为 `yarn generate` 即可更新 markdown 文件。

`./lib/generate.js` 是基于您之前 csl-development 仓库里的，不过您用了好几个数据源，我当时匆匆忙忙的也没细看，就只留了一个 `gbt-7714`，您看如果有需要补的可以补进去。

目前我觉得就只有个“样式链接”需要处理一下，其余的大方向上基本符合我的预想了，您看看有什么建议呢？


（主要是我之前改 csl 也没考虑过示例数据的问题，也没用过脚本，就是改完重启 zotero，然后 word 拉几篇文献看看效果，所以对你们经常维护 csl 的工作流并不大了解，可能会出现我折腾完反而不方便你们了的情况）

**Comment by zepinglee** [comment]
> `./lib/generate.js` 是基于您之前 csl-development 仓库里的，不过您用了好几个数据源，我当时匆匆忙忙的也没细看，就只留了一个 `gbt-7714`，您看如果有需要补的可以补进去。

OK，这个交给我。这里的“好几个数据源”是什么意思？

> 目前我觉得就只有个“样式链接”需要处理一下，其余的大方向上基本符合我的预想了，您看看有什么建议呢？
>
> （主要是我之前改 csl 也没考虑过示例数据的问题，也没用过脚本，就是改完重启 zotero，然后 word 拉几篇文献看看效果，所以对你们经常维护 csl 的工作流并不大了解，可能会出现我折腾完反而不方便你们了的情况）

其实我们也没有统一的工作流。我自己是在 csl-development 中进行修改，利用 git 跟踪进行回归测试。不过 @redleafnew 似乎是在 Zotero 中进行测试的。

**Comment by zepinglee** [comment]
我注意到 `src/` 目录下分了 [dependent](https://github.com/zotero-cn/styles/tree/main/src/dependent), [gb-t-7714-2015](https://github.com/zotero-cn/styles/tree/main/src/gb-t-7714-2015) 和 [independent](https://github.com/zotero-cn/styles/tree/main/src/independent) 几个目录。其实 gb-t-7714-2015 和 independent 中的内容没有明显界限，比如 independent/303gb-t-7714-2015-note-bilingual 其实是 GB/T 7714—2015 的脚注式，建议放都到一个目录中。另外 dependent 样式对于 zotero-cn 这样的非官方仓库似乎也没什么意义，不妨直接去掉。

**Comment by northword** [comment]
> 这里的“好几个数据源”是什么意思？

https://github.com/zepinglee/csl-development 里，存在 [test-data.json](https://github.com/zepinglee/csl-development/blob/main/test-data.json) 、[gbt7714-data.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-data.json) 两个条目信息数据集合，[gbt7714-cites-author-date.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-cites-author-date.json)，[gbt7714-cites-note.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-cites-note.json)，[gbt7714-cites-numeric.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-cites-numeric.json)，[test-cites.json](https://github.com/zepinglee/csl-development/blob/main/test-cites.json) 四个引文列表，但我理解的是，无论什么样式，都是用一个条目数据集合和一个引文列表，这一点不用区分是顺序编码还是作者-年份。仅对于一些特殊的样式可以适配不同的条目数据和引文列表。

> 其实 gb-t-7714-2015 和 independent 中的内容没有明显界限，比如 independent/303gb-t-7714-2015-note-bilingual 其实是 GB/T 7714—2015 的脚注式，建议放都到一个目录中。

这个是移动时候漏掉了

> 另外 dependent 样式对于 zotero-cn 这样的非官方仓库似乎也没什么意义，不妨直接去掉。

我最开始想的是，很多学校的学位论文都是基于国标的，可以建立依赖样式，不过想想确实没啥必要，那就可以去掉了。
去掉 dependent 后，independent 其实也不必要单独成文件夹，可以改为


```
src.
├─gt-t-7714-2015
│  ├─numnic
│  │  ├─gb-t-7714-2015-numeric-bilingual.csl
│  │  └─README.md
│  ├─author-data
│  └─...
├─ cms
├─ tcas
├─ ieee-bl
├─ ...
```
类似这种？

**Comment by zepinglee** [comment]
> > 这里的“好几个数据源”是什么意思？
> 
> https://github.com/zepinglee/csl-development 里，存在 [test-data.json](https://github.com/zepinglee/csl-development/blob/main/test-data.json) 、[gbt7714-data.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-data.json) 两个条目信息数据集合，[gbt7714-cites-author-date.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-cites-author-date.json)，[gbt7714-cites-note.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-cites-note.json)，[gbt7714-cites-numeric.json](https://github.com/zepinglee/csl-development/blob/main/gbt7714-cites-numeric.json)，[test-cites.json](https://github.com/zepinglee/csl-development/blob/main/test-cites.json) 四个引文列表，但我理解的是，无论什么样式，都是用一个条目数据集合和一个引文列表，这一点不用区分是顺序编码还是作者-年份。仅对于一些特殊的样式可以适配不同的条目数据和引文列表。

numeric, author-date, note 三类样式的文后参考文献表确实差异不大，但是文中的引用标注的特性则完全不同。比如 numeric 需要关注引用连续编号是否省略（`[1, 2-4]`）， author-date 需要关注作者的姓名有没有消歧义（disambiguation）、年份有没有 collapse（如“(R. Doe 1984a, 1984b; J. Doe , 2010)”），而 note 式需要关注重复引用是否省略（比如“同上”、“ibid.”）。但是，用一套引文列表就很难同时展示三种样式的特性。比如 numeric 示例 “[1-3]”，换成 note 样式就要连续显示三篇文献的完整内容，这么长的内容一眼看过去很混乱。

当然，以上对于测试尤为重要，对于示例而言，限于篇幅也不太可能完全展示出来，所以并不是很紧要。可以等我有空时再改一下。

> > 其实 gb-t-7714-2015 和 independent 中的内容没有明显界限，比如 independent/303gb-t-7714-2015-note-bilingual 其实是 GB/T 7714—2015 的脚注式，建议放都到一个目录中。
> 
> 这个是移动时候漏掉了
> 
> > 另外 dependent 样式对于 zotero-cn 这样的非官方仓库似乎也没什么意义，不妨直接去掉。
> 
> 我最开始想的是，很多学校的学位论文都是基于国标的，可以建立依赖样式，不过想想确实没啥必要，那就可以去掉了。 去掉 dependent 后，independent 其实也不必要单独成文件夹，可以改为
> 
> ```
> src.
> ├─gt-t-7714-2015
> │  ├─numnic
> │  │  ├─gb-t-7714-2015-numeric-bilingual.csl
> │  │  └─README.md
> │  ├─author-data
> │  └─...
> ├─ cms
> ├─ tcas
> ├─ ieee-bl
> ├─ ...
> ```
> 
> 类似这种？

嗯，跟我想的一样。

**Comment by northword** [comment]
> numeric, author-date, note 三类样式的文后参考文献表确实差异不大，但是文中的引用标注的特性则完全不同。比如 numeric 需要关注引用连续编号是否省略（`[1, 2-4]`）， author-date 需要关注作者的姓名有没有消歧义（disambiguation）、年份有没有 collapse（如“(R. Doe 1984a, 1984b; J. Doe , 2010)”），而 note 式需要关注重复引用是否省略（比如“同上”、“ibid.”）。但是，用一套引文列表就很难同时展示三种样式的特性。比如 numeric 示例 “[1-3]”，换成 note 样式就要连续显示三篇文献的完整内容，这么长的内容一眼看过去很混乱。
> 
> 当然，以上对于测试尤为重要，对于示例而言，限于篇幅也不太可能完全展示出来，所以并不是很紧要。可以等我有空时再改一下。

原来是这样，明白了
