### ISSUE TITLE
author-date 样式悬挂缩进的显示效果

### ISSUE THREAD

**Issue by zepinglee** [zotero-cn/styles#7]
author-date 的参考文献表通常使用悬挂缩进（`<bibliography>` 中会设置悬挂 `hang-indent="true"`），`citeproc.makeBibliography()` 返回的参数重没有 `second-field-align` 项，比如这里会生成 `second-field-align-undefined`。

https://github.com/zotero-cn/styles/blob/347f0efdf21eaf18f3f831924f568126f6bfff51/src/gb-t-7714-2015/001gb-t-7714-2015-author-date-bilingual/README.md?plain=1#L23

正确的效果是这样的：
<img width="692" alt="Screen Shot 2022-08-19 at 19 57 53" src="https://user-images.githubusercontent.com/12290822/185613598-7f585587-4823-48df-adc8-c44fd574ef34.png">

另外这里的 `<div class="csl-entry>` 怎么压缩成一行了？我觉得展开成多行更容易阅读 diff。

还有请教一个问题，在本地 build 是使用 `yarn run build:vite` 吗（用于测试效果）？我 build 的效果是这样的，似乎有些什么元素没正确加载。
<img width="673" alt="Screen Shot 2022-08-19 at 20 15 48" src="https://user-images.githubusercontent.com/12290822/185616457-f70383dd-d32b-407c-812c-56a97bcc3a3c.png">

**Comment by northword** [comment]
> author-date 的参考文献表通常使用悬挂缩进（`<bibliography>` 中会设置悬挂 `hang-indent="true"`），`citeproc.makeBibliography()` 返回的参数重没有 `second-field-align` 项，比如这里会生成 `second-field-align-undefined`。
> 

收到。

> 
> 另外这里的 `<div class="csl-entry>` 怎么压缩成一行了？我觉得展开成多行更容易阅读 diff。
> 

大约是少加了个`\n`，我之后改一下。

> 还有请教一个问题，在本地 build 是使用 `yarn run build:vite` 吗（用于测试效果）？我 build 的效果是这样的，似乎有些什么元素没正确加载。 

本地 `yarn dev:vite` 即可，这样有更改的可以热重载，不用再 build 一次，在 [README](https://github.com/zotero-cn/styles#%E8%BF%90%E8%A1%8C) 里有提到。

通常，本地都是 dev ，上线才 build 。dev 时候也可以在浏览器里 f12 查看源码。

如果要用 build 的话，访问时候需要加 [base](https://v2.vuepress.vuejs.org/zh/reference/config.html#base)：styles ，因为网页里面的 CSS 路径都是绝对路径，直接访问会获取不到，需要在本地启动一个网页服务器，例如 localhost/styles/ 。

**Comment by northword** [comment]
如果你使用 VS Code ，可以在这里快速运行命令：
![image](https://user-images.githubusercontent.com/44738481/185726891-ebcb31b0-f2ea-4202-a3c1-268a1cc4bc12.png)

**Comment by northword** [comment]
请教一下，这种是应该是应该悬挂两字符（红线）还是应该和绿线齐？

![image](https://user-images.githubusercontent.com/44738481/185727935-b7adf6e2-b476-49f7-b788-795a38efaa52.png)

**Comment by zepinglee** [comment]
> > author-date 的参考文献表通常使用悬挂缩进（`<bibliography>` 中会设置悬挂 `hang-indent="true"`），`citeproc.makeBibliography()` 返回的参数重没有 `second-field-align` 项，比如这里会生成 `second-field-align-undefined`。
> 
> 收到。
> 
> > 另外这里的 `<div class="csl-entry>` 怎么压缩成一行了？我觉得展开成多行更容易阅读 diff。
> 
> 大约是少加了个`\n`，我之后改一下。
> 
> UPDATE：已修改
> 
> > 还有请教一个问题，在本地 build 是使用 `yarn run build:vite` 吗（用于测试效果）？我 build 的效果是这样的，似乎有些什么元素没正确加载。
> 
> 本地 `yarn dev:vite` 即可，这样有更改的可以热更新，不用再 build 一次，在 [README](https://github.com/zotero-cn/styles#%E8%BF%90%E8%A1%8C) 里有提到。
> 
> 通常，本地都是 dev ，上线才 build 。dev 时候也可以在浏览器里 f12 查看源码。
> 
> 如果要用 build 的话，访问时候需要加 [base](https://v2.vuepress.vuejs.org/zh/reference/config.html#base)：styles ，因为网页里面的 CSS 路径都是绝对路径，直接访问会获取不到，需要在本地启动一个网页服务器，例如 localhost/styles/ 。

感谢，试了一下成功了。

**Comment by zepinglee** [comment]
> 请教一下，这种是应该是应该悬挂两字符（红线）还是应该和绿线齐？
> 
> ![image](https://user-images.githubusercontent.com/44738481/185727935-b7adf6e2-b476-49f7-b788-795a38efaa52.png)

很奇怪，带序号的参考文献表一般是使用 `second-field-align="flush"` 对齐的，`hang-indent` 只要求续行缩进一定宽度，一般不要求跟第一行的内容对齐。

我看了一下 [202journal-of-management-world.csl](https://github.com/zotero-cn/styles/blob/main/src/202journal-of-management-world/202journal-of-management-world.csl) 中的官方格式链接，其中要求的效果是普通的段落缩进，.csl 中不应该设置 `hang-indent`。所以 css 的效果没问题，csl 样式需要修改这个错误。

<img width="713" alt="Screen Shot 2022-08-20 at 18 00 55" src="https://user-images.githubusercontent.com/12290822/185740504-a6297538-42ea-4c3a-9fec-70f085d885c0.png">

**Comment by northword** [comment]
收到，谢谢！
