### ISSUE TITLE
src/ 目录结构

### ISSUE THREAD

**Issue by zepinglee** [zotero-cn/styles#8]
我注意到目前的目录中保留了 [src/gb-t-7714-2015](https://github.com/zotero-cn/styles/tree/main/src/gb-t-7714-2015) 目录。这个似乎没有没有必要单独保留。一是大部分学位论文和理工科学报都是基于 GB/T 7714 的，二是像《法学引注手册》明确指出 GB/T 7714 又叫“学报体”，不适用本学科，所以 GB/T 7714 并没有特殊的地位。

**Comment by northword** [comment]
我是想着很多学位论文就是国标顺序编码/作者年份等的某一种，基本没有改变，放在一起可能更好找一些。如果确实没必要保留的话，就把他移出来就好。

**Comment by zepinglee** [comment]
那按照期刊｜学位论文｜GB/T 7714 这样分类？比如

```
src
├── gb-t-7714
├── journals
└── theses
```

有的法学院的学位论文其实使用的是《法学引注手册》，不完全是 GB/T 7714。

**Comment by northword** [comment]
《法学引注手册》会用于期刊吗？如果仅用于学位论文，那这样分类就可以。如果他还用于期刊，那我觉得还是按上面讨论的，把国标移出来，所有样式都在 src/ 下吧？

**Comment by zepinglee** [comment]
> 《法学引注手册》会用于期刊吗？如果仅用于学位论文，那这样分类就可以。如果他还用于期刊，那我觉得还是按上面讨论的，把国标移出来，所有样式都在 src/ 下吧？

会的。

<img width="682" alt="Screen Shot 2022-08-20 at 18 19 15" src="https://user-images.githubusercontent.com/12290822/185741494-d6f62572-e2a1-4593-b1a2-4cabb614e923.png">

**Comment by northword** [comment]
那我们就还是所有的样式都放在同一级吧。vuepress-theme-hope 的作者对多标签筛选特性也比较感兴趣，如果这个特性可以实现，我们就可以为每个样式打“学位论文”、“国标”等的标签进行分类筛选。

**Comment by zepinglee** [comment]
嗯，有了多标签就更方便了。

**Comment by zepinglee** [comment]
赞！
