### ISSUE TITLE
“引文”、“书目”等术语

### ISSUE THREAD

**Issue by zepinglee** [zotero-cn/styles#9]
目前在各个样式的 markdown 预览中使用了“引文”和“书目”，建议改为“引注”和“参考文献表”。

GB/T 7714 中使用了“正文中引用的文献的标注方法……”和“参考文献表”的称法；《法学引注手册》中则将 citation 称为“引注”。

**Comment by zepinglee** [comment]
另外，网站的标题应该是“CSL 中文样式”不是“Zotero 中文样式”。

**Comment by northword** [comment]
收到，我改一下。
